repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.45"
    hooks:
    -   id: check-manifest
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3.9
        exclude: setup.py
