language: python

env:
  - ENV=travis

python:
  - "3.6"
  - "3.7"
  - "3.8"

os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - os: windows
    - os: osx

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .

script:
  - py.test --cov esmigrate --cov-report term-missing

after_success:
  - codecov

branches:
  only:
    - master
